# Generated by Django 4.0.4 on 2022-05-10 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Figurine', 'Figurine'), ('House Furnitures', 'House Furnitures'), ('Jewelry', 'Jewelry'), ('Painting', 'Painting'), ('Plushie', 'Plushie')], max_length=32),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='auctions.category'),
        ),
    ]
