# Generated by Django 4.0.4 on 2022-05-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_category_name_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Initial', 'Select the category'), ('Figurine', 'Figurine'), ('House Furnitures', 'House Furnitures'), ('Jewelry', 'Jewelry'), ('Painting', 'Painting'), ('Plushie', 'Plushie')], max_length=32),
        ),
    ]
