# Generated by Django 4.0.4 on 2022-05-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('initial', 'choose'), ('Figurine', 'Figurine'), ('House Furnitures', 'House Furnitures'), ('Jewelry', 'Jewelry'), ('Painting', 'Painting'), ('Plushie', 'Plushie')], max_length=32),
        ),
    ]
