# Generated by Django 4.0.4 on 2022-05-14 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_category_name_alter_listing_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='watched_by',
            new_name='watcher',
        ),
    ]
